name: slider_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  carousel_slider: ^4.2.1
  dio: ^4.0.6
  hooks_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - resources/images/
